// Static UI string table for the two supported languages.
//
// Content that varies per surgery/plan/case (tier + plan names, treatment
// details) is NOT here — that already ships bilingual in data.ts / the endpoint
// and is resolved via pick() in i18n.tsx. This table only covers the fixed UI
// chrome (labels, buttons, headings, the WhatsApp message scaffolding).
//
// `en` is the source of truth for the key set; `zh` is typed as
// Record<StringKey, string> so a missing translation is a COMPILE error.
// Templated strings carry {tokens} that callers fill via String.replace.

export type Lang = 'en' | 'zh';

const en = {
  // ── shared / reused across components ──
  'common.male': 'Male',
  'common.female': 'Female',
  'common.any': 'Any',
  'common.anyAge': 'Any age',
  'common.allGenders': 'All genders',
  'common.allAges': 'All ages',
  'common.none': 'None',
  'common.dayCase': 'Day case',
  'common.noCap': 'No cap',
  'common.perMonth': '/mo',
  'common.removeFromComparison': 'Remove from comparison',
  'common.addToComparison': 'Add to comparison',
  'ward.standard': 'Standard ward',
  'ward.semi-private': 'Semi-private',
  'ward.private': 'Private',

  // ── top bar ──
  'topbar.toolBadge': 'Claim Comparison',
  'topbar.quotes': 'Quotes',
  'topbar.quotesTitle': 'Show indicative monthly premiums',
  'topbar.clearAll': 'Clear all',

  // ── left rail tabs ──
  'rail.about': 'About me',
  'rail.plan': 'Plan',
  'rail.case': 'Case',
  'about.intro':
    'Tell us a little about yourself to see an indicative monthly premium for each plan. This stays separate from the case filters.',

  // ── loading / error gates ──
  'gate.loading': 'Loading operation data…',
  'gate.errorTitle': 'Couldn’t load operation data',
  'gate.errorHint': 'Check that you can reach the operation-data endpoint, then try again.',
  'gate.retry': 'Retry',

  // ── coverage chart ──
  'chart.title': 'Coverage breakdown',
  'chart.splitBill': 'How each plan splits the bill',
  'chart.holdsUpTpl': 'How {plan} holds up across surgeries',
  'chart.holdsUpGeneric': 'How one plan holds up across surgeries',
  'chart.pickCasesTitle': 'Pick cases to compare',
  'chart.pickCasesSub': 'Choose surgeries in the Case tab on the left',
  'chart.pickPlansTitle': 'Pick VHIS plans',
  'chart.pickPlansSub': 'Choose plans in the Plan tab on the left',
  'chart.showDetails': 'Show coverage details',
  'chart.hideDetails': 'Hide coverage details',
  'chart.eligibleCharge': 'Eligible medical charge',
  'chart.deductible': 'Deductible',
  'chart.youPayFirst': 'You pay this first',
  'chart.aboveLimit': 'Above plan limit',
  'chart.vhisCovers': 'VHIS covers',
  'chart.vhisReimburses': 'VHIS reimburses',
  'chart.dedYouPayFirst': 'Deductible · you pay first',
  'chart.aboveLimitYouPay': 'Above plan limit · you pay',
  'chart.netPayout': 'Net payout',
  'chart.netPayoutSub': 'VHIS pays the hospital / you',
  'chart.youPayTotal': 'You pay in total',
  'chart.fullyCovered': 'HK$0 · fully covered',
  'chart.monthlyPremium': 'Monthly premium',
  'chart.noPerSurgeryLimit': 'No per-surgery limit',
  'chart.planLimitPerSurgeryTpl': 'Plan limit {amount} per surgery',
  'chart.feeSurgeon': 'Surgeon’s fee',
  'chart.feeAnaesthetist': 'Anaesthetist’s fee',
  'chart.feeTheatre': 'Operating theatre charges',
  'chart.feeSmm': 'SMM coverage',
  'chart.smmBreakdownTpl': '{remaining} remaining after surgeon’s, anaesthetist’s & theatre fees × {pct}%',
  'chart.feeCombinedSurgical': 'Surgeon’s, anaesthetist’s & theatre fees (combined)',
  'chart.scheduleLoading': 'Calculating coverage…',
  'chart.scheduleErrorTitle': 'Couldn’t calculate coverage',
  'chart.tierSurgeryTpl': '{tier} surgery',
  'chart.estMedicalCharge': 'Est. medical charge',
  'chart.rangeNoteTpl': 'Medium estimate · {tier} range {range}',
  'chart.usualStay': 'Usual hospital stay',
  'chart.noOvernight': 'No overnight',
  'chart.inpatient': 'Inpatient',
  'chart.night': 'night',
  'chart.nights': 'nights',
  'chart.planLabel': 'Plan',
  'chart.capsEachClaim': 'Caps each claim',
  'chart.perSurgeryLimit': 'Per-surgery limit',
  'chart.wardClass': 'Ward class',
  'chart.annualTpl': 'Annual {amount}',
  'chart.internal': 'Internal',
  'chart.internalDetails': 'Internal details',
  'chart.internalTreatmentDetails': 'Internal treatment details',
  'chart.internalOnlyTreatmentDetails': 'Internal-only treatment details',
  'chart.removeThisPlan': 'Remove this plan',

  // ── coverage tabs bar ──
  'tabs.cases': 'Cases',
  'tabs.plans': 'Plans',
  'tabs.pickCasesHint': 'Pick surgeries in the Case tab →',
  'tabs.pickPlansHint': 'Pick plans in the Plan tab →',

  // ── case tab ──
  'case.title': 'Case',
  'case.sub': 'Pick the surgery examples to compare',
  'case.surgeryTier': 'Surgery tier',
  'case.realExamples': 'Real examples',
  'case.inThisTierTpl': '({n} in this tier)',
  'case.gender': 'Gender',
  'case.age': 'Age',
  'case.noMatching': 'No matching cases',

  // ── plan tab ──
  'plan.configure': 'Configure',
  'plan.addToCompare': 'Add VHIS plans to compare',
  'plan.vhisPlans': 'VHIS plans',
  'plan.selectedTpl': '({n} selected)',
  'plan.noDeduct': 'No deduct.',
  'plan.deductTpl': 'Deduct {amount}',
  'plan.pinkPlan': 'Pink plan',
  'plan.pinkHint': 'Tap ward × deductible to compare',
  'plan.pinkBulkSuffix': 'Get all quotes',
  'plan.remove': 'Remove',
  'plan.addShort': 'Add to compare',

  // ── profile form ──
  'profile.nonSmoker': 'Non-smoker',
  'profile.smoker': 'Smoker',
  'profile.age': 'Age',
  'profile.selectBirthYear': 'Select birth year',
  'profile.year': 'Year',
  'profile.yrs': 'yrs',
  'profile.month': 'Month',
  'profile.optional': 'optional',
  'profile.notSpecified': 'Not specified',
  'profile.cancel': 'Cancel',
  'profile.apply': 'Apply',
  'profile.pickByBirthYear': 'Pick by birth year',

  // ── internal detail modal ──
  'modal.internalOnly': 'Internal only · not shown to customers',
  'modal.close': 'Close',
  'modal.whoGetsThis': 'Who gets this',
  'modal.ageGroup': 'Age group',
  'modal.gender': 'Gender',
  'modal.aboutOperation': 'About the operation',
  'modal.operationPurpose': 'Operation purpose',
  'modal.operationIntro': 'Operation introduction',
  'modal.estOperationTime': 'Estimated operation time',
  'modal.chargeReference': 'Private hospital charge reference',
  'modal.inRider': 'In rider',
  'modal.notInRider': 'Not in rider',
  'modal.officialName': 'Official name',
  'modal.dayCaseInpatient': 'Day case / inpatient',
  'modal.priceRange': 'Price (range)',

  // ── message panel: chrome ──
  'msg.title': 'Message',
  'msg.showMessage': 'Show message',
  'msg.collapse': 'Collapse',
  'msg.subByCase': 'WhatsApp to customer · ready to send',
  'msg.subByPlan': 'WhatsApp · one plan across surgeries',
  'msg.placeholder': 'Pick a case + plans to generate a message...',
  'msg.chars': 'chars',
  'msg.edited': '· edited',
  'msg.copied': '✓ Copied',
  'msg.copy': 'Copy',

  // ── message panel: generated WhatsApp body ──
  'msg.greetingCase': 'Hi! Here’s a quick example of what your surgery could cost:',
  'msg.procedure': 'Procedure: ',
  'msg.estTotal': 'Estimated total: ',
  'msg.refProfile': 'Reference profile: ',
  'msg.comparison': 'VHIS plan comparison:',
  'msg.deductible': 'Deductible: ',
  'msg.vhisPays': 'VHIS pays: ',
  'msg.youPay': 'You pay: ',
  'msg.calculating': '(calculating…)',
  'msg.unavailable': '(coverage unavailable)',
  'msg.fullyCovered': '  — fully covered',
  'msg.closing': 'Let me know if you have any questions — happy to walk through it.',
  'msg.greetingPlanTpl': 'Hi! Here’s how {plan} would cover you across different surgeries:',
  'msg.plan': 'Plan: ',
  'msg.perSurgeryLimit': 'Per-surgery limit: ',
  'msg.ward': 'Ward: ',
  'msg.coverageBySurgery': 'Coverage by surgery:',
  'msg.perSurgeryCapTpl': '{amount} per surgery',
} as const;

export type StringKey = keyof typeof en;

const zh: Record<StringKey, string> = {
  // ── shared / reused across components ──
  'common.male': '男',
  'common.female': '女',
  'common.any': '不限',
  'common.anyAge': '不限年齡',
  'common.allGenders': '所有性別',
  'common.allAges': '所有年齡',
  'common.none': '無',
  'common.dayCase': '日間手術',
  'common.noCap': '無上限',
  'common.perMonth': '/月',
  'common.removeFromComparison': '從比較中移除',
  'common.addToComparison': '加入比較',
  'ward.standard': '普通病房',
  'ward.semi-private': '半私家房',
  'ward.private': '私家房',

  // ── top bar ──
  'topbar.toolBadge': '賠償比較',
  'topbar.quotes': '報價',
  'topbar.quotesTitle': '顯示參考每月保費',
  'topbar.clearAll': '全部清除',

  // ── left rail tabs ──
  'rail.about': '關於我',
  'rail.plan': '計劃',
  'rail.case': '個案',
  'about.intro':
    '告訴我們一些關於你的基本資料，即可查看每個計劃的參考每月保費。此資料與個案篩選分開處理。',

  // ── loading / error gates ──
  'gate.loading': '正在載入手術資料…',
  'gate.errorTitle': '無法載入手術資料',
  'gate.errorHint': '請確認能連接手術資料端點後再試一次。',
  'gate.retry': '重試',

  // ── coverage chart ──
  'chart.title': '保障分析',
  'chart.splitBill': '各計劃如何分擔費用',
  'chart.holdsUpTpl': '{plan} 在不同手術下的保障表現',
  'chart.holdsUpGeneric': '單一計劃在不同手術下的保障表現',
  'chart.pickCasesTitle': '選擇要比較的個案',
  'chart.pickCasesSub': '在左方「個案」分頁選擇手術',
  'chart.pickPlansTitle': '選擇自願醫保計劃',
  'chart.pickPlansSub': '在左方「計劃」分頁選擇計劃',
  'chart.showDetails': '顯示保障詳情',
  'chart.hideDetails': '隱藏保障詳情',
  'chart.eligibleCharge': '合資格醫療費用',
  'chart.deductible': '墊底費',
  'chart.youPayFirst': '你需先支付',
  'chart.aboveLimit': '超出計劃上限',
  'chart.vhisCovers': '自願醫保賠償',
  'chart.vhisReimburses': '自願醫保賠償',
  'chart.dedYouPayFirst': '墊底費 · 你先支付',
  'chart.aboveLimitYouPay': '超出計劃上限 · 你支付',
  'chart.netPayout': '淨賠償額',
  'chart.netPayoutSub': '自願醫保支付予醫院／你',
  'chart.youPayTotal': '你需支付總額',
  'chart.fullyCovered': 'HK$0 · 全數保障',
  'chart.monthlyPremium': '每月保費',
  'chart.noPerSurgeryLimit': '每次手術無上限',
  'chart.planLimitPerSurgeryTpl': '每次手術計劃上限 {amount}',
  'chart.feeSurgeon': '外科醫生費',
  'chart.feeAnaesthetist': '麻醉科醫生費',
  'chart.feeTheatre': '手術室費用',
  'chart.feeSmm': '主要醫療補充保障（SMM）',
  'chart.smmBreakdownTpl': '扣除外科醫生費、麻醉科醫生費及手術室費後餘額 {remaining} × {pct}%',
  'chart.feeCombinedSurgical': '外科醫生費、麻醉科醫生費及手術室費（合併）',
  'chart.scheduleLoading': '正在計算保障…',
  'chart.scheduleErrorTitle': '無法計算保障',
  'chart.tierSurgeryTpl': '{tier}',
  'chart.estMedicalCharge': '預計醫療費用',
  'chart.rangeNoteTpl': '中位估算 · {tier}範圍 {range}',
  'chart.usualStay': '一般住院時間',
  'chart.noOvernight': '毋須過夜',
  'chart.inpatient': '住院',
  'chart.night': '晚',
  'chart.nights': '晚',
  'chart.planLabel': '計劃',
  'chart.capsEachClaim': '限制每次索償',
  'chart.perSurgeryLimit': '每次手術上限',
  'chart.wardClass': '病房級別',
  'chart.annualTpl': '每年 {amount}',
  'chart.internal': '內部',
  'chart.internalDetails': '內部詳情',
  'chart.internalTreatmentDetails': '內部治療詳情',
  'chart.internalOnlyTreatmentDetails': '僅供內部的治療詳情',
  'chart.removeThisPlan': '移除此計劃',

  // ── coverage tabs bar ──
  'tabs.cases': '個案',
  'tabs.plans': '計劃',
  'tabs.pickCasesHint': '在「個案」分頁選擇手術 →',
  'tabs.pickPlansHint': '在「計劃」分頁選擇計劃 →',

  // ── case tab ──
  'case.title': '個案',
  'case.sub': '選擇要比較的手術例子',
  'case.surgeryTier': '手術類別',
  'case.realExamples': '真實例子',
  'case.inThisTierTpl': '（此類別中有 {n} 個）',
  'case.gender': '性別',
  'case.age': '年齡',
  'case.noMatching': '沒有符合的個案',

  // ── plan tab ──
  'plan.configure': '設定',
  'plan.addToCompare': '加入自願醫保計劃作比較',
  'plan.vhisPlans': '自願醫保計劃',
  'plan.selectedTpl': '（已選 {n} 個）',
  'plan.noDeduct': '無墊底費',
  'plan.deductTpl': '墊底費 {amount}',
  'plan.pinkPlan': '粉紅計劃',
  'plan.pinkHint': '點選病房 × 墊底費作比較',
  'plan.pinkBulkSuffix': '一鍵取得全系列報價',
  'plan.remove': '移除',
  'plan.addShort': '加入比較',

  // ── profile form ──
  'profile.nonSmoker': '非吸煙',
  'profile.smoker': '吸煙',
  'profile.age': '年齡',
  'profile.selectBirthYear': '選擇出生年份',
  'profile.year': '年份',
  'profile.yrs': '歲',
  'profile.month': '月份',
  'profile.optional': '選填',
  'profile.notSpecified': '不指定',
  'profile.cancel': '取消',
  'profile.apply': '套用',
  'profile.pickByBirthYear': '按出生年份選擇',

  // ── internal detail modal ──
  'modal.internalOnly': '僅供內部 · 不會向客戶顯示',
  'modal.close': '關閉',
  'modal.whoGetsThis': '哪些人適用',
  'modal.ageGroup': '年齡組別',
  'modal.gender': '性別',
  'modal.aboutOperation': '關於手術',
  'modal.operationPurpose': '手術目的',
  'modal.operationIntro': '手術簡介',
  'modal.estOperationTime': '預計手術時間',
  'modal.chargeReference': '私家醫院收費參考',
  'modal.inRider': '包含於附加保障',
  'modal.notInRider': '不包含於附加保障',
  'modal.officialName': '正式名稱',
  'modal.dayCaseInpatient': '日間手術／住院',
  'modal.priceRange': '價格（範圍）',

  // ── message panel: chrome ──
  'msg.title': '訊息',
  'msg.showMessage': '顯示訊息',
  'msg.collapse': '收合',
  'msg.subByCase': 'WhatsApp 給客戶 · 可直接傳送',
  'msg.subByPlan': 'WhatsApp · 單一計劃跨手術',
  'msg.placeholder': '選擇個案及計劃以生成訊息…',
  'msg.chars': '字',
  'msg.edited': '· 已編輯',
  'msg.copied': '✓ 已複製',
  'msg.copy': '複製',

  // ── message panel: generated WhatsApp body ──
  'msg.greetingCase': '你好！以下是這項手術的預計費用參考：',
  'msg.procedure': '手術：',
  'msg.estTotal': '預計總額：',
  'msg.refProfile': '參考資料：',
  'msg.comparison': '自願醫保計劃比較：',
  'msg.deductible': '墊底費：',
  'msg.vhisPays': '自願醫保賠償：',
  'msg.youPay': '你需支付：',
  'msg.calculating': '（計算中…）',
  'msg.unavailable': '（保障資料暫時無法計算）',
  'msg.fullyCovered': '  — 全數保障',
  'msg.closing': '如有任何疑問，歡迎隨時聯絡我們了解詳情。',
  'msg.greetingPlanTpl': '你好！以下是 {plan} 在不同手術下的保障：',
  'msg.plan': '計劃：',
  'msg.perSurgeryLimit': '每次手術上限：',
  'msg.ward': '病房：',
  'msg.coverageBySurgery': '各手術保障：',
  'msg.perSurgeryCapTpl': '每次手術 {amount}',
};

export const STRINGS: Record<Lang, Record<StringKey, string>> = { en, zh };
